/** @type {import('next-sitemap').IConfig} */
const ALLOW = new Set([
  '/',
  '/about',
  '/services',
  '/pricing',
  '/portfolio',
  '/work',
  '/work/buildwellz',
  '/work/crystal-knot-films',
  '/work/squeeze-berriez',
  '/work/mangrove-moments',
  '/work/mangrove-spot',
  '/work/lemon-caters',
  '/work/kerala-sellers',
  '/digital-product-solutions-reviews',
  '/contact',
  '/book',
  '/website-development',
  '/website-maintenance-kerala',
  '/software-development',
  '/app-development',
  '/app-development-kerala',
  '/seo-services',
  '/business-automation',
  '/ai-powered-solutions',
  '/social-media-management',
  '/ecommerce-website-development-kerala',
  '/whatsapp-automation-kerala',
  '/affordable-website-development-trivandrum',
  '/website-developer-trivandrum',
  '/website-development-trivandrum',
  '/website-development-cost-kerala',
  '/small-business-website-kerala',
  '/website-redesign-trivandrum',
  '/website-cost-calculator',
  '/project-cost-estimator',
  '/affordable-ecommerce-website-kerala',
  '/online-store-development-trivandrum',
  '/ecommerce-website-cost-kerala',
  '/clinic-website-development-kerala',
  '/hospital-website-development-kerala',
  '/construction-website-development-kerala',
  '/school-website-development-kerala',
  '/startup-mvp-development-kerala',
  '/freelance-web-developer-kerala',
  '/dedicated-developer-team-kerala',
  '/outsource-web-development-kerala',
  '/restaurant-website-online-ordering-kerala',
  '/website-development-for-hotels-resorts-kerala',
  '/real-estate-builder-website-development-kerala',
  '/website-development-for-hospitals-clinics-kerala',
  '/ai-chatbot-development-kerala',
  '/digital-marketing-trivandrum',
  '/local-seo-kerala',
  '/seo-for-doctors-clinics-kerala',
  '/google-ads-management-kerala',
  '/odoo-erp-development-kerala',
  '/school-education-management-software-kerala',
  '/real-estate-crm-lead-management-kerala',
  '/travel-agency-crm-kerala',
  '/education-admission-crm-kerala',
  '/car-dealer-crm-kerala',
  '/crm-software-kerala',
  '/wedding-planner-crm-kerala',
  '/photography-crm-kerala',
  '/interior-design-crm-kerala',
  '/gym-crm-kerala',
  '/furniture-crm-kerala',
  '/ai-agent-rag-development-india',
  '/software-development-trivandrum',
  '/kerala-sellers',
  '/digital-marketing-kollam',
  '/digital-marketing-kozhikode',
  '/seo-services-kannur',
  '/web-development-kottayam',
  '/web-development-palakkad',
  '/all-pages',
  '/blog',
  '/blog/ai-powered-digital-solutions-business-growth',
  '/blog/custom-ecommerce-software-sales',
  '/blog/responsive-web-design-clients',
  '/blog/cloud-based-digital-solutions',
  '/blog/seo-critical-digital-product-success',
  '/blog/secure-digital-products-cybersecurity',
  '/blog/future-ux-design-digital-solutions',
  '/blog/data-analytics-business-decisions',
  '/blog/choose-right-digital-solution',
  '/blog/apis-digital-product-development',
  '/blog/ai-driven-marketing-solutions',
  '/blog/microservices-ecommerce-development',
  '/blog/optimize-website-voice-search',
  '/blog/scalable-web-applications-nextjs',
  '/blog/5g-digital-product-performance',
  '/blog/ai-chatbots-ecommerce-store',
  '/blog/content-marketing-digital-success',
  '/blog/optimizing-web-performance',
  '/blog/accessibility-digital-products',
  '/blog/blockchain-security-digital-solutions',
  '/blog/top-trends-digital-product-development',
  '/blog/ab-testing-digital-products',
  '/blog/devops-digital-development',
  '/blog/future-proof-business-digital-innovation',
  '/blog/low-code-platforms-rapid-development',
  '/blog/website-cost-kerala-2026',
  '/blog/whatsapp-automation-restaurants-kerala',
  '/blog/ai-chatbots-clinics-kerala',
  '/blog/local-seo-checklist-kerala',
  '/blog/odoo-erp-kerala-manufacturers',
  '/blog/ayurvedic-clinic-website-kerala',
  '/blog/digital-marketing-hotels-kerala',
  '/blog/freelancer-vs-development-team-kerala',
  '/blog/wordpress-vs-custom-website-kerala',
  '/blog/website-vs-landing-page-kerala',
  '/blog/seo-vs-google-ads-kerala',
  '/blog/whatsapp-automation-vs-manual-kerala',
  '/blog/how-to-create-website-small-business-kerala',
  '/blog/how-to-sell-online-kerala',
  '/blog/how-to-choose-a-website-developer-kerala',
  '/blog/app-development-cost-kerala',
  '/blog/software-development-cost-kerala',
  '/blog/seo-cost-kerala',
  '/privacy-policy',
  '/terms-of-service',
  '/data-deletion',
  '/freelance-software-developer-kerala',
  '/hotel-booking-website-kerala',
  '/homestay-booking-website-kerala',
  '/jewellery-website-kerala',
  '/salon-booking-website-kerala',
  '/interior-designer-website-kerala',
  '/gym-membership-website-kerala',
  '/manufacturing-website-kerala',
  '/car-rental-website-kerala',
  '/coaching-centre-website-kerala',
  '/logistics-website-kerala',
  '/photography-website-kerala',
  '/online-booking-website-kerala',
  '/travel-agency-website-kerala',
  '/real-estate-website-kerala',
  '/furniture-shop-website-kerala',
  '/car-showroom-website-kerala',
  '/wedding-planner-website-kerala',
  '/professional-service-website-kerala',
]);

module.exports = {
  siteUrl: 'https://www.digitalproductsolutions.in',
  generateRobotsTxt: false,
  generateIndexSitemap: false,
  outDir: 'out',
  changefreq: 'weekly',
  priority: 0.7,
  sitemapSize: 5000,
  exclude: [
    '/admin',
    '/private',
    '/api',
    '/certificate-verified',
    '/website-emi-kerala',
    '/seo-services-kerala',
    '/ai-services',
    '/ai-automation-for-businesses-kerala',
  ],
  transform: async (config, path) => {
    if (!ALLOW.has(path)) return null;
    return {
      loc: path,
      changefreq: 'weekly',
      priority: path === '/' ? 1.0 : path.startsWith('/blog/') ? 0.6 : 0.8,
    };
  },
  additionalPaths: async (config) => {
    const extra = [];
    for (const path of ALLOW) {
      extra.push(await config.transform(config, path));
    }
    return extra.filter(Boolean);
  },
};

module.exports.allowPaths = [...ALLOW];
