export const htmlSitemapGroups: { heading: string; links: { href: string; label: string }[] }[] = [
  {
    heading: "Company & Trust",
    links: [
      { href: "/", label: "Home (Digital Product Solutions)" },
      { href: "/about", label: "About Our Kerala Team" },
      { href: "/work", label: "Client Case Studies & Work Stories" },
      { href: "/digital-product-solutions-reviews", label: "Verified Reviews & Ratings" },
      { href: "/portfolio", label: "Live Projects Portfolio" },
      { href: "/services", label: "All Services Overview" },
      { href: "/pricing", label: "Transparent Pricing Plans" },
      { href: "/contact", label: "Contact Us (Direct Developer Access)" },
      { href: "/book", label: "Book a Consultation" },
      { href: "/certificate-verified", label: "MSME & Registered Verification" },
      { href: "/all-pages", label: "All Pages Directory" },
    ],
  },
  {
    heading: "Web & Software Development Services",
    links: [
      { href: "/website-development", label: "Website Development Kerala" },
      { href: "/website-developer-trivandrum", label: "Website Developer in Trivandrum" },
      { href: "/website-development-trivandrum", label: "Web Development Agency Trivandrum" },
      { href: "/affordable-website-development-trivandrum", label: "Affordable Websites in Trivandrum" },
      { href: "/small-business-website-kerala", label: "Small Business Website Development" },
      { href: "/freelance-software-developer-kerala", label: "Freelance Software Developer Kerala" },
      { href: "/freelance-web-developer-kerala", label: "Freelance Web Developer Kerala" },
      { href: "/dedicated-developer-team-kerala", label: "Hire Dedicated Developers in Kerala" },
      { href: "/outsource-web-development-kerala", label: "Outsource Web Development to Kerala" },
      { href: "/software-development", label: "Custom Software Development" },
      { href: "/software-development-trivandrum", label: "Software Development Company Trivandrum" },
      { href: "/startup-mvp-development-kerala", label: "Startup MVP App & Web Development" },
      { href: "/website-maintenance-kerala", label: "Website Maintenance & Support Kerala" },
      { href: "/website-redesign-trivandrum", label: "Website Redesign Trivandrum" },
      { href: "/website-development-cost-kerala", label: "Website Cost in Kerala (2026 Guide)" },
      { href: "/website-cost-calculator", label: "Interactive Website Cost Calculator" },
      { href: "/project-cost-estimator", label: "Project Cost Estimator Tool" },
      { href: "/website-emi-kerala", label: "Monthly EMI Website Packages" },
    ],
  },
  {
    heading: "Mobile Apps & AI Automation",
    links: [
      { href: "/app-development", label: "Mobile App Development (Android & iOS)" },
      { href: "/app-development-kerala", label: "App Development Company Kerala" },
      { href: "/ai-services", label: "AI Services & Business Integration" },
      { href: "/ai-powered-solutions", label: "AI Powered Digital Solutions" },
      { href: "/ai-chatbot-development-kerala", label: "AI Chatbot Development for Kerala Businesses" },
      { href: "/ai-automation-for-businesses-kerala", label: "AI Business Automation Systems" },
      { href: "/ai-agent-rag-development-india", label: "AI Agent & RAG System Development India" },
      { href: "/whatsapp-automation-kerala", label: "WhatsApp Business API & Automation Kerala" },
      { href: "/business-automation", label: "End-to-End Business Automation" },
      { href: "/kerala-sellers", label: "Kerala Sellers Marketplace Platform" },
    ],
  },
  {
    heading: "E-Commerce Solutions",
    links: [
      { href: "/ecommerce-website-development-kerala", label: "E-Commerce Website Development Kerala" },
      { href: "/affordable-ecommerce-website-kerala", label: "Affordable E-Commerce Store Solutions" },
      { href: "/online-store-development-trivandrum", label: "Online Store Development Trivandrum" },
      { href: "/ecommerce-website-cost-kerala", label: "E-Commerce Website Cost Breakdown Kerala" },
    ],
  },
  {
    heading: "SEO & Digital Marketing",
    links: [
      { href: "/seo-services", label: "Best SEO Company in Kerala" },
      { href: "/seo-services-kerala", label: "SEO Services Across Kerala" },
      { href: "/local-seo-kerala", label: "Local Google Maps SEO Kerala" },
      { href: "/google-ads-management-kerala", label: "Google Ads & PPC Management Kerala" },
      { href: "/digital-marketing-trivandrum", label: "Best Digital Marketing Company Trivandrum" },
      { href: "/digital-marketing-kollam", label: "Digital Marketing Agency Kollam" },
      { href: "/digital-marketing-kozhikode", label: "Digital Marketing Agency Kozhikode" },
      { href: "/seo-services-kannur", label: "SEO Services in Kannur" },
      { href: "/web-development-kottayam", label: "Web Development in Kottayam" },
      { href: "/web-development-palakkad", label: "Web Development in Palakkad" },
      { href: "/seo-for-doctors-clinics-kerala", label: "SEO for Doctors & Clinics Kerala" },
      { href: "/social-media-management", label: "Social Media Management Kerala" },
    ],
  },
  {
    heading: "Kerala Industry CRM Software",
    links: [
      { href: "/crm-software-kerala", label: "CRM Software Kerala (Central Hub)" },
      { href: "/real-estate-crm-lead-management-kerala", label: "Real Estate CRM & Lead Management" },
      { href: "/travel-agency-crm-kerala", label: "Travel Agency Booking & Inquiry CRM" },
      { href: "/education-admission-crm-kerala", label: "Education & College Admission CRM" },
      { href: "/car-dealer-crm-kerala", label: "Used Car Dealer & Showroom CRM" },
      { href: "/furniture-crm-kerala", label: "Furniture Store Order & Quotation CRM" },
      { href: "/gym-crm-kerala", label: "Gym Membership & Renewal CRM" },
      { href: "/interior-design-crm-kerala", label: "Interior Design Project Tracking CRM" },
      { href: "/photography-crm-kerala", label: "Photography & Studio Booking CRM" },
      { href: "/wedding-planner-crm-kerala", label: "Wedding & Event Planner CRM" },
      { href: "/construction-crm-kerala", label: "Construction Contractor CRM" },
      { href: "/clinic-management-software-kerala", label: "Clinic Appointment & Patient Management" },
      { href: "/jewellery-crm-kerala", label: "Jewellery Customer Loyalty CRM" },
      { href: "/odoo-erp-development-kerala", label: "Odoo ERP Implementation Kerala" },
    ],
  },
  {
    heading: "Kerala Industry Websites",
    links: [
      { href: "/clinic-website-development-kerala", label: "Doctor & Clinic Websites Kerala" },
      { href: "/hospital-website-development-kerala", label: "Hospital & Medical Centre Websites" },
      { href: "/website-development-for-hospitals-clinics-kerala", label: "Hospital & Healthcare Web Systems" },
      { href: "/school-website-development-kerala", label: "School & Educational Institution Websites" },
      { href: "/school-education-management-software-kerala", label: "School Education Management Software" },
      { href: "/construction-website-development-kerala", label: "Builders & Construction Websites" },
      { href: "/real-estate-builder-website-development-kerala", label: "Real Estate Builder & Project Websites" },
      { href: "/real-estate-website-kerala", label: "Real Estate Listing Websites" },
      { href: "/hotel-booking-website-kerala", label: "Hotel & Resort Direct Booking Websites" },
      { href: "/website-development-for-hotels-resorts-kerala", label: "Hotels & Luxury Resorts Web Solutions" },
      { href: "/homestay-booking-website-kerala", label: "Kerala Homestay Booking Websites" },
      { href: "/restaurant-website-online-ordering-kerala", label: "Restaurant Online Food Ordering Websites" },
      { href: "/travel-agency-website-kerala", label: "Tour Operator & Travel Websites" },
      { href: "/jewellery-website-kerala", label: "Jewellery Brand Catalog Websites" },
      { href: "/salon-booking-website-kerala", label: "Salon & Spa Appointment Websites" },
      { href: "/interior-designer-website-kerala", label: "Interior Designer Portfolio Websites" },
      { href: "/gym-membership-website-kerala", label: "Fitness Centre & Gym Websites" },
      { href: "/manufacturing-website-kerala", label: "Factory & Manufacturer B2B Websites" },
      { href: "/car-rental-website-kerala", label: "Self-Drive & Car Rental Websites" },
      { href: "/car-showroom-website-kerala", label: "Automobile Dealership Websites" },
      { href: "/coaching-centre-website-kerala", label: "Tuition & Coaching Academy Websites" },
      { href: "/logistics-website-kerala", label: "Freight & Logistics Company Websites" },
      { href: "/photography-website-kerala", label: "Wedding Photography Portfolio Websites" },
      { href: "/online-booking-website-kerala", label: "Appointment & Service Booking Websites" },
      { href: "/furniture-shop-website-kerala", label: "Furniture Showroom Catalog Websites" },
      { href: "/wedding-planner-website-kerala", label: "Event & Wedding Management Websites" },
      { href: "/professional-service-website-kerala", label: "Lawyer, CA & Consultant Websites" },
      { href: "/vehicle-service-website-kerala", label: "Automobile Service & Garage Websites" },
    ],
  },
  {
    heading: "Kerala Business Guides & Blog",
    links: [
      { href: "/blog", label: "All Insights & Blog Articles" },
      { href: "/blog/website-cost-kerala-2026", label: "Website Development Cost in Kerala (2026 Breakdown)" },
      { href: "/blog/ai-chatbots-clinics-kerala", label: "AI Chatbots for Kerala Clinics & Hospitals" },
      { href: "/blog/whatsapp-automation-restaurants-kerala", label: "WhatsApp Automation for Kerala Restaurants" },
      { href: "/blog/odoo-erp-kerala-manufacturers", label: "Odoo ERP for Kerala Manufacturers & Traders" },
      { href: "/blog/ayurvedic-clinic-website-kerala", label: "Ayurvedic Clinics Digital Growth Strategy" },
      { href: "/blog/digital-marketing-hotels-kerala", label: "Digital Marketing for Kerala Hotels & Resorts" },
      { href: "/blog/local-seo-checklist-kerala", label: "Complete Kerala Local SEO Checklist" },
      { href: "/blog/how-to-create-website-small-business-kerala", label: "How to Create a Small Business Website in Kerala" },
      { href: "/blog/how-to-sell-online-kerala", label: "How to Sell Online in Kerala: Complete E-commerce Guide" },
      { href: "/blog/app-development-cost-kerala", label: "Mobile App Development Cost in Kerala" },
      { href: "/blog/website-vs-landing-page-kerala", label: "Website vs Landing Page: Which is Best for Your Business?" },
      { href: "/blog/software-development-cost-kerala", label: "Custom Software Development Cost in Kerala" },
      { href: "/blog/ai-powered-digital-solutions-business-growth", label: "AI Powered Digital Solutions for Business Growth" },
    ],
  },
  {
    heading: "Compliance & Policies",
    links: [
      { href: "/privacy-policy", label: "Privacy Policy (DPDP Act & Meta Tech Provider Compliant)" },
      { href: "/terms-of-service", label: "Terms of Service" },
      { href: "/data-deletion", label: "Data Deletion Instructions" },
    ],
  },
];
